// TS-native BN254 Poseidon via circomlibjs — matches circuits/lib_bn254's
// CommitmentHasher and MerkleProof templates exactly (same widths, same
// circomlib constants), and matches the on-chain Poseidon2 contract
// (contracts/arc/src/Poseidon2Bytecode.json, generated by the same
// circomlibjs). This replaces the Rust `stellar-coinutils` binary's
// hand-rolled Poseidon255 implementation for the Arc/BN254 path.

// @ts-ignore - circomlibjs has no types
import { buildPoseidon } from "circomlibjs";

export const BN254_FIELD_MODULUS =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

let poseidonPromise: Promise<any> | null = null;
function getPoseidon(): Promise<any> {
  if (!poseidonPromise) poseidonPromise = buildPoseidon();
  return poseidonPromise as Promise<any>;
}

/** Poseidon over `inputs.length` field elements (matches circomlib's `Poseidon(n)`). */
export async function poseidonHash(inputs: bigint[]): Promise<bigint> {
  const poseidon = await getPoseidon();
  return poseidon.F.toObject(poseidon(inputs)) as bigint;
}

/** Synchronous Poseidon(2), for use once the instance is warmed via `warmPoseidon()`. */
export function makeSyncHash2(poseidon: any): (a: bigint, b: bigint) => bigint {
  return (a: bigint, b: bigint) => poseidon.F.toObject(poseidon([a, b])) as bigint;
}

export async function warmPoseidon(): Promise<any> {
  return getPoseidon();
}

export type CommitmentParts = {
  commitment: bigint;
  nullifierHash: bigint;
  precommitment: bigint;
  assetValueLabel: bigint;
};

/**
 * Matches circuits/lib_bn254/commitment.circom's CommitmentHasher exactly:
 *   precommitment    = Poseidon(nullifier, secret)
 *   assetValueLabel  = Poseidon(assetId, value, label)
 *   commitment       = Poseidon(assetValueLabel, precommitment)
 *   nullifierHash    = Poseidon(nullifier)
 */
export async function commitmentHasher(
  assetId: bigint,
  value: bigint,
  label: bigint,
  nullifier: bigint,
  secret: bigint
): Promise<CommitmentParts> {
  const precommitment = await poseidonHash([nullifier, secret]);
  const assetValueLabel = await poseidonHash([assetId, value, label]);
  const commitment = await poseidonHash([assetValueLabel, precommitment]);
  const nullifierHash = await poseidonHash([nullifier]);
  return { commitment, nullifierHash, precommitment, assetValueLabel };
}

/** Domain-separated nullifier hash: Poseidon(nullifier, poolId, chainId). */
export async function domainNullifierHash(nullifier: bigint, poolId: bigint, chainId: bigint): Promise<bigint> {
  return poseidonHash([nullifier, poolId, chainId]);
}
