// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "./PoseidonDeployer.sol";
import "./mocks/MockVerifiers.sol";
import "./mocks/MockERC20.sol";
import "../src/ShieldedPool.sol";
import "../src/NullifierRegistry.sol";
import "../src/verifiers/TransferVerifier.sol";
import "../src/interfaces/IVerifiers.sol";

/**
 * @title PoolIntegrationTest
 * @notice FULL end-to-end integration: a REAL private_transfer BN254 proof
 *         (generated by scripts/circuits-test-arc.ts with circomlibjs Poseidon)
 *         settles through the ACTUAL ShieldedPool + REAL TransferVerifier +
 *         REAL on-chain Poseidon Merkle tree — no mock on the ZK path.
 *
 * Critically, this also proves the on-chain frontier tree produces the EXACT
 * same root as the circuit's in-witness Merkle computation: after seeding the
 * pool with the circuit's input commitment, pool.getRoot() == the proof's
 * stateRoot public signal. If the tree and circuit disagreed by one hash, the
 * `isKnownRoot(stateRoot)` check would fail.
 *
 * Scenario data: test/transfer_scenario.json (regenerated by circuits:test:arc).
 */
contract PoolIntegrationTest is PoseidonDeployer {
    ShieldedPool pool;
    NullifierRegistry nullReg;
    TransferVerifier transferVerifier; // REAL snarkjs verifier
    MockVerifier mockDeposit;          // only to seed the tree
    MockERC20 usdc;

    address admin = address(0xA11CE);

    // loaded from scenario json
    uint256 inCommitment;
    uint256 scenarioStateRoot;
    uint256 scenarioAssoc;
    uint256 scenarioPoolId;
    uint256 scenarioChainId;
    uint256[2] a;
    uint256[2][2] b;
    uint256[2] c;
    uint256[9] input;

    uint256 USDC_ASSET;

    function setUp() public {
        string memory json = vm.readFile("test/transfer_scenario.json");
        inCommitment = vm.parseJsonUint(json, ".inCommitment");
        scenarioStateRoot = vm.parseJsonUint(json, ".stateRoot");
        scenarioAssoc = vm.parseJsonUint(json, ".associationRoot");
        scenarioPoolId = vm.parseJsonUint(json, ".poolId");
        scenarioChainId = vm.parseJsonUint(json, ".chainId");

        uint256[] memory av = vm.parseJsonUintArray(json, ".a");
        a[0] = av[0]; a[1] = av[1];
        uint256[] memory b0 = vm.parseJsonUintArray(json, ".b[0]");
        uint256[] memory b1 = vm.parseJsonUintArray(json, ".b[1]");
        b[0][0] = b0[0]; b[0][1] = b0[1]; b[1][0] = b1[0]; b[1][1] = b1[1];
        uint256[] memory cv = vm.parseJsonUintArray(json, ".c");
        c[0] = cv[0]; c[1] = cv[1];
        uint256[] memory iv = vm.parseJsonUintArray(json, ".input");
        for (uint256 i = 0; i < 9; i++) input[i] = iv[i];

        vm.startPrank(admin);
        IPoseidon2 poseidon2 = deployPoseidon2();
        nullReg = new NullifierRegistry(admin);
        pool = new ShieldedPool(admin, address(nullReg), scenarioPoolId, scenarioChainId, 12, poseidon2);
        nullReg.setAuthorizedSpender(address(pool), true);

        transferVerifier = new TransferVerifier();
        mockDeposit = new MockVerifier();
        pool.setTransferVerifier(address(transferVerifier)); // REAL
        pool.setDepositVerifier(address(mockDeposit));        // seed only

        usdc = new MockERC20();
        USDC_ASSET = uint256(sha256(abi.encodePacked(address(usdc)))) >> 8;
        pool.registerAsset(USDC_ASSET, address(usdc));
        usdc.mint(address(pool), 1_000_000);
        pool.setAssociationRoot(scenarioAssoc);
        vm.stopPrank();
    }

    function _hashToField(bytes32 h) internal pure returns (uint256) {
        return uint256(sha256(abi.encodePacked(h))) >> 8;
    }

    // seed the pool tree with the circuit's input commitment at leaf 0
    function _seedInputCommitment() internal {
        bytes32 nonce = bytes32(uint256(1));
        uint256[14] memory pub;
        pub[0] = inCommitment; // the leaf that goes into the tree
        pub[1] = 4;
        pub[2] = 3;
        pub[3] = 27;
        pub[4] = _hashToField(nonce);
        pub[5] = 0xB0;
        pub[6] = 100;
        pub[7] = 1000;
        pub[8] = uint256(sha256(abi.encodePacked(address(usdc)))) >> 8;
        pub[9] = uint256(sha256(abi.encodePacked(address(pool)))) >> 8;
        pub[10] = _hashToField(bytes32(uint256(0xE0)));
        pub[11] = _hashToField(bytes32(uint256(0xF0)));
        pub[12] = scenarioPoolId;
        pub[13] = scenarioChainId;
        Groth16Proof memory p;
        vm.prank(admin);
        pool.receiveDeposit(3, nonce, address(usdc), 1000, inCommitment, 0xE0, 0xF0, p, pub);
    }

    /// The on-chain frontier tree root EXACTLY matches the circuit's stateRoot.
    function test_onchain_root_matches_circuit_stateRoot() public {
        _seedInputCommitment();
        assertEq(pool.getRoot(), scenarioStateRoot, "on-chain root != circuit stateRoot");
        assertTrue(pool.isKnownRoot(scenarioStateRoot), "circuit stateRoot not known on-chain");
    }

    /// A REAL private_transfer proof settles through the actual pool.
    function test_real_proof_settles_through_pool() public {
        _seedInputCommitment();

        Groth16Proof memory proof = Groth16Proof({a: a, b: b, c: c});
        uint256 leavesBefore = pool.getLeafCount();

        vm.prank(admin);
        pool.privateTransferSettle(proof, input);

        // input nullifier spent, output commitment inserted
        assertTrue(nullReg.isSpent(bytes32(input[0])), "input nullifier not spent");
        assertEq(pool.getLeafCount(), leavesBefore + 1, "output note not inserted");
    }

    /// A tampered public signal (feePublic) makes the real verifier reject.
    function test_real_proof_tampered_rejected() public {
        _seedInputCommitment();
        Groth16Proof memory proof = Groth16Proof({a: a, b: b, c: c});
        uint256[9] memory bad = input;
        bad[2] = bad[2] + 1; // change feePublic
        vm.prank(admin);
        vm.expectRevert(ShieldedPool.ProofInvalid.selector);
        pool.privateTransferSettle(proof, bad);
    }
}
