// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/verifiers/TransferVerifier.sol";

/**
 * @title TransferVerifierTest
 * @notice Phase 1 on-chain proof: the snarkjs-generated BN254 Groth16 verifier
 *         accepts a REAL proof (built by scripts/circuits-test-arc.ts with
 *         circomlibjs Poseidon) and rejects a tampered public signal. This is the
 *         direct BN254/EVM analog of the BLS12-381/Soroban spike documented in
 *         docs/zk-proof-system.md ("Verifier contract — DEPLOYED AND PROVEN").
 *
 * The proof calldata is regenerated by `npm run circuits:test:arc` into
 * test/transfer_calldata.json.
 */
contract TransferVerifierTest is Test {
    TransferVerifier verifier;

    uint256[2] a;
    uint256[2][2] b;
    uint256[2] c;
    uint256[9] input;

    function setUp() public {
        verifier = new TransferVerifier();

        string memory json = vm.readFile("test/transfer_calldata.json");

        uint256[] memory av = vm.parseJsonUintArray(json, ".a");
        a[0] = av[0];
        a[1] = av[1];

        uint256[] memory b0 = vm.parseJsonUintArray(json, ".b[0]");
        uint256[] memory b1 = vm.parseJsonUintArray(json, ".b[1]");
        b[0][0] = b0[0];
        b[0][1] = b0[1];
        b[1][0] = b1[0];
        b[1][1] = b1[1];

        uint256[] memory cv = vm.parseJsonUintArray(json, ".c");
        c[0] = cv[0];
        c[1] = cv[1];

        uint256[] memory iv = vm.parseJsonUintArray(json, ".input");
        for (uint256 i = 0; i < 9; i++) {
            input[i] = iv[i];
        }
    }

    /// Invariant 1: a real BN254 Groth16 proof verifies on-chain -> TRUE.
    function test_valid_proof_verifies_onchain() public view {
        assertTrue(verifier.verifyProof(a, b, c, input), "valid proof should verify on-chain");
    }

    /// Invariant 2: tampering ANY public signal makes the verifier reject -> FALSE.
    function test_tampered_public_signal_rejected() public view {
        uint256[9] memory bad = input;
        bad[1] = bad[1] ^ 1; // flip a bit in outputCommitment
        assertFalse(verifier.verifyProof(a, b, c, bad), "tampered signal must be rejected");
    }

    /// Tampering the nullifierHash (output signal [0]) is also rejected.
    function test_tampered_nullifier_rejected() public view {
        uint256[9] memory bad = input;
        bad[0] = bad[0] ^ 1;
        assertFalse(verifier.verifyProof(a, b, c, bad), "tampered nullifier must be rejected");
    }
}
